2023-06-14 14:21:37,400 - dydxClient - ERROR - An error occurred while initialize dydx client: HTTPSConnectionPool(host='api.dydx.exchange', port=443): Max retries exceeded with url: /v3/accounts/4420b5d4-396e-5a73-bae4-5b00098df41a (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f151fe77220>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-06-14 14:22:39,223 - dydxClient - ERROR - An error occurred while initialize dydx client: HTTPSConnectionPool(host='api.dydx.exchange', port=443): Max retries exceeded with url: /v3/accounts/4420b5d4-396e-5a73-bae4-5b00098df41a (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f151fe77520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-06-14 14:22:39,223 - dydxClient - ERROR - An error occurred while initialize dydx client: HTTPSConnectionPool(host='api.dydx.exchange', port=443): Max retries exceeded with url: /v3/accounts/4420b5d4-396e-5a73-bae4-5b00098df41a (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f151fe77520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-06-14 14:23:25,000 - dydxClient - ERROR - An error occurred while initialize dydx client: HTTPSConnectionPool(host='api.dydx.exchange', port=443): Max retries exceeded with url: /v3/accounts/4420b5d4-396e-5a73-bae4-5b00098df41a (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f151fd33790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-06-14 14:23:25,000 - dydxClient - ERROR - An error occurred while initialize dydx client: HTTPSConnectionPool(host='api.dydx.exchange', port=443): Max retries exceeded with url: /v3/accounts/4420b5d4-396e-5a73-bae4-5b00098df41a (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f151fd33790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-06-14 14:23:25,000 - dydxClient - ERROR - An error occurred while initialize dydx client: HTTPSConnectionPool(host='api.dydx.exchange', port=443): Max retries exceeded with url: /v3/accounts/4420b5d4-396e-5a73-bae4-5b00098df41a (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f151fd33790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
